In [ ]:
# Packages
import pandas as pd

# Repository root path
root = 2 * "../"

In [26]:
minute_data = pd.read_csv(root + "data/ppm/ori/minute.csv")
print(f"Minute Data Range: {minute_data['DateTime'][0]} ~ {minute_data['DateTime'][minute_data.shape[0]-1]}")
print(f"Minute Data Shape: {minute_data.shape}")
minute_data.head()

Minute Data Range: 2016-01-01 12:04:00 ~ 2021-12-31 23:59:00
Minute Data Shape: (3086701, 13)

,DateTime,Raw_Flow,Raw_temperature,Raw_electrical conductivity,Raw_turbidity,Raw_alkalinity,Raw_pH,Raw_TOC,PAC,Pre_chlorine,Sed_chlorine,Sed_turbidity,Mid_chlorine
0,2016-01-01 12:04:00,2375.00,8.900,188.053097,2.025,33.25,7.1750,1.668937,13.721414,2.30,1.03,0.27,0.5
1,2016-01-01 12:05:00,2375.00,8.875,188.191882,2.050,33.25,7.1750,1.668937,13.236815,2.28,1.04,0.27,0.5
2,2016-01-01 12:06:00,2383.75,8.875,188.191882,2.050,33.25,7.1785,1.668937,12.605561,2.28,1.04,0.27,0.5
3,2016-01-01 12:07:00,2376.25,8.875,188.560886,2.050,33.25,7.1785,1.668937,11.576227,2.29,1.04,0.27,0.5
4,2016-01-01 12:08:00,2382.50,8.875,188.191882,2.000,33.25,7.1750,1.668937,11.600207,2.31,1.04,0.27,0.5

In [25]:
hour_data = pd.read_csv(root + "data/ppm/ori/hour.csv")

print(f"Hour Data Range: {hour_data['DateTime'][0]} ~ {hour_data['DateTime'][hour_data.shape[0]-1]}")
print(f"Hour Data Shape: {hour_data.shape}")
hour_data.head()

Hour Data Range: 2016-01-01 12:00:00 ~ 2021-12-31 23:00:00
Hour Data Shape: (52596, 13)

,DateTime,Raw_Flow,Raw_temperature,Raw_electrical conductivity,Raw_turbidity,Raw_alkalinity,Raw_pH,Raw_TOC,PAC,Pre_chlorine,Sed_chlorine,Sed_turbidity,Mid_chlorine
0,2016-01-01 12:00:00,2375.00,8.907143,186.921133,1.928125,33.250446,7.175125,1.668937,10.961077,2.291607,1.038750,0.270000,0.513036
1,2016-01-01 13:00:00,2576.25,8.935417,185.874105,1.697917,35.263333,7.170042,1.668937,10.942969,2.291667,1.050667,0.270000,0.530000
2,2016-01-01 14:00:00,2586.25,8.954167,187.624267,1.859167,32.963750,7.162517,1.668937,10.876959,2.291167,1.064333,0.270000,0.533000
3,2016-01-01 15:00:00,2525.00,8.957083,185.638802,2.089167,33.228750,7.173308,1.668937,10.994690,2.291167,1.030000,0.270333,0.525500
4,2016-01-01 16:00:00,2455.00,8.956667,183.033574,2.204167,32.404167,7.182467,1.668937,11.109072,2.293167,1.016500,0.271500,0.534500